/**
 * Token parsing shared by the scanner and the manual-entry fallback.
 *
 * Accepts whatever a servant is likely to have:
 *   • the bare 64-char token copied from the admin UI, or
 *   • the full check-in URL that the QR contains
 *   • a trailing slash / extra query string are tolerated
 *
 * Pure module (no React, no server imports) so client components can use it.
 */

/** The shape of a token generated by `generateQrToken()` (64 hex chars). */
const TOKEN_RE = /^[a-f0-9]{16,128}$/i;

export function isQrTokenShape(value: string): boolean {
  return TOKEN_RE.test(value.trim());
}

/** Extract the check-in token from a scanned value or a pasted URL. */
export function extractCheckinToken(value: string): string | null {
  const raw = value.trim();
  if (!raw) return null;

  if (isQrTokenShape(raw)) return raw.toLowerCase();

  try {
    const url = new URL(raw, "https://example.invalid");
    const segments = url.pathname.split("/").filter(Boolean);
    const markerIndex = segments.indexOf("checkin");
    const candidate =
      markerIndex >= 0 ? segments[markerIndex + 1] : segments[segments.length - 1];
    if (candidate && isQrTokenShape(candidate)) return candidate.toLowerCase();
  } catch {
    /* not a URL — fall through */
  }

  return null;
}
