import type { Metadata, Viewport } from "next";
import "./globals.css";
import { siteConfig, themeConfig } from "@/config";

const { pwaIcons } = siteConfig.assets;

export const metadata: Metadata = {
  title: siteConfig.name,
  description: siteConfig.description.en,
  /** Single authoritative manifest (see `src/app/manifest.ts`). */
  manifest: "/manifest.webmanifest",
  /**
   * Exact-size icons generated by `npm run generate-icons` into `public/icons/`
   * and declared with their real pixel sizes — so a browser never downloads the
   * 1254px source artwork (`siteConfig.assets.appIcon`) to paint a 16px tab icon.
   */
  icons: {
    icon: [
      { url: pwaIcons.icon48, sizes: "48x48", type: "image/png" },
      { url: pwaIcons.icon192, sizes: "192x192", type: "image/png" },
      { url: pwaIcons.icon512, sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: pwaIcons.appleTouch180, sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  /** Same value as the manifest `theme_color` (installed status-bar tint). */
  themeColor: themeConfig.colors.dark,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return children;
}
