import type { Metadata, Viewport } from "next";
import "./globals.css";
import { siteConfig, themeConfig } from "@/config";
import { localizedValue } from "@/lib/localized";
import { DEFAULT_LOCALE } from "@/i18n/locales";

const { pwaIcons } = siteConfig.assets;

/**
 * Root layout metadata.
 *
 * This is only a FALLBACK for routes that render outside `[locale]` (the
 * empty `/` page, the standalone `/checkin` and `/admin` subtrees, which each
 * provide their own <html>). Every localized page under `[locale]/…` exports
 * `generateMetadata()` from `@/i18n/metadata`, so /en/… and /ar/… get their
 * own title, description, canonical URL and hreflang alternates.
 */
export const metadata: Metadata = {
  title: localizedValue(siteConfig.name, DEFAULT_LOCALE),
  description: localizedValue(siteConfig.description, DEFAULT_LOCALE),
  /** Single authoritative manifest (see `src/app/manifest.ts`). */
  manifest: "/manifest.webmanifest",
  /**
   * Exact-size icons generated by `npm run generate-icons` into `public/icons/`
   * and declared with their real pixel sizes — so a browser never downloads the
   * 1254px source artwork (`siteConfig.assets.appIcon`) to paint a 16px tab icon.
   */
  icons: {
    icon: [
      { url: pwaIcons.icon48, sizes: "48x48", type: "image/png" },
      { url: pwaIcons.icon192, sizes: "192x192", type: "image/png" },
      { url: pwaIcons.icon512, sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: pwaIcons.appleTouch180, sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  /**
   * The page background, so the mobile status bar / browser chrome matches the
   * page instead of showing a dark brown band above the tan. Same value as the
   * manifest `theme_color` (installed status-bar tint).
   */
  themeColor: themeConfig.colors.pageBackground,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return children;
}
